services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama-spiritus
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    image: open-webui:custom
    container_name: open-webui-spiritus
    env_file:
      - .env
    volumes:
      - openwebui_spiritus:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3030}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: keycloak-db-spiritus
    volumes:
      - keycloak_spiritus:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD-keycloak_password}
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-spiritus
    command: start-dev   #sur server Dev
    #command: ["start"]   #sur server prod
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD-keycloak_password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD-admin}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: auth.chatspiritus.com
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      # (recommand√©)
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: INFO
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  ollama: {}
  openwebui_spiritus: {}
  keycloak_spiritus: {}
